# Generated by Django 3.2.3 on 2021-05-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fuelType', models.CharField(max_length=299)),
                ('horsePower', models.IntegerField()),
                ('cylinders', models.IntegerField()),
                ('driveTrain', models.CharField(max_length=299)),
                ('numDoors', models.IntegerField()),
                ('size', models.CharField(max_length=299)),
                ('style', models.CharField(max_length=299)),
                ('highwayMpg', models.IntegerField()),
                ('cityMpg', models.IntegerField()),
                ('msrp', models.IntegerField()),
            ],
        ),
    ]
