# Generated by Django 3.2.3 on 2021-05-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fuelType', models.CharField(max_length=299)),
                ('horsePower', models.IntegerField(blank=True, null=True)),
                ('cylinders', models.IntegerField(blank=True, null=True)),
                ('driveTrain', models.CharField(max_length=299)),
                ('numDoors', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(max_length=299)),
                ('style', models.CharField(max_length=299)),
                ('highwayMpg', models.IntegerField()),
                ('cityMpg', models.IntegerField()),
                ('msrp', models.IntegerField()),
            ],
        ),
    ]
